require 'ostruct'

require 'aasm/version'
require 'aasm/errors'
require 'aasm/configuration'
require 'aasm/base'
require 'aasm/dsl_helper'
require 'aasm/instance_base'
require 'aasm/core/transition'
require 'aasm/core/event'
require 'aasm/core/state'
require 'aasm/localizer'
require 'aasm/state_machine'
require 'aasm/persistence'
require 'aasm/aasm'
